Ocramius/PackageVersions

- README.md
- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
Users should just re-dump the autoloader via `composer dump-autoload --optimize` manually (post-install)
This logic caused other plugins to conflict (see https://github.com/puli/issues/issues/183#issuecomment-189282691 )
> Remove autoload re-dump optimization

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
- test/PackageVersionsTest/VersionsTest.php
Temporary workaround for composer/composer#5237 - avoids regex parsing of a class template
> Workaround for composer/composer#5237 - class parsing

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
Composer already registers listeners when the plugin class implements EventSubscriberInterface
closes #30
> Remove double registration of the event listeners

- .gitignore
- .travis.yml
- src/PackageVersions/FallbackVersions.php
- src/PackageVersions/Versions.php
- test/PackageVersionsTest/FallbackVersionsTest.php
> Fix for #18 -  support running with --no-scripts flag

- composer.json
- src/PackageVersions/Installer.php
- test/PackageVersionsTest/E2EInstallerTest.php
- test/PackageVersionsTest/InstallerTest.php
I had to refactor a little to reduce repeating code, anyway this fixes #38.
However, I've had a think and I don't know how we can provide an e2e test. We could provide some project assets but we'd have to mess with the systems global composer project, which I don't think we can do safely.
I've also had to modify existing tests, I wasn't sure how to get them working now that we need `ocramius/package-versions` to be present in the locker.
Thoughts @Ocramius ?
> Ignore the global plugin when updating local projects

- .gitattributes
- .gitignore
- .travis.yml
- composer.json
- humbug.json.dist
- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
This PR enforces mutation testing on the package.
> Mutation testing, PHP 7.1 testing

- .travis.yml
- composer.json
- test/PackageVersionsTest/E2EInstallerTest.php
- test/PackageVersionsTest/FallbackVersionsTest.php
- test/PackageVersionsTest/InstallerTest.php
- test/PackageVersionsTest/VersionsTest.php
As we support `PHP 7`, I've updated our suite of tests to `PHPUnit 6`.
> Update to PHPUnit 6

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
This is needed to fix issues such as https://github.com/Symplify/Symplify/pull/589
> Support Composers "replaces" config, important for CI in mono repos

- src/PackageVersions/FallbackVersions.php
- src/PackageVersions/Installer.php
- src/PackageVersions/Versions.php
- test/PackageVersionsTest/InstallerTest.php
Fixes https://github.com/Ocramius/PackageVersions/issues/55.
> Expose root package name

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
As promised in https://github.com/Ocramius/PackageVersions/pull/57#discussion_r165918151
[EDIT] Double push is due to rebase on master
> Parse self.version in replaced packages

- .travis.yml
This should be a trivial fix for the recent `nightly` issue (popped up in #65), without allowing mystical 8.0-dev in composer.json.
> Test against PHP 7.3 and 7.4snapshot, drop nightly

- src/PackageVersions/Installer.php
Running a composer update with this lib included renders a message into the console.
this message has 1 space to much on the left, which will be removed with this PR:
> fixed spacing

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
the constant is public for technical reasons, therefore should be documented as `@internal`.
Added a hint for the public api to use
> added docs to Versions::VERSION

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
As described by @muglug in https://github.com/vimeo/psalm/releases/tag/3.3.1, it is now possible to statically check parameters given to `PackageVersions\Versions::getVersion()`.
@malukenho what do you think of this?
Few questions are open for discussion here:
1. do we care about dynamic package names? Calls like `PackageVersions\Versions::getVersion($aString)` will now fail if downstream won't force it to be an `/** @var key-of \PackageVersions\Versions::VERSIONS $aString */`
2. Do we still need the `\OutOfBoundsException`, if the access can be statically checked?
> Provide `@psalm-param key-of<self::VERSIONS>` type-check for downstream

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
the Readme describes that you should use the `--optimize` flag when dumping the autoloader.
this package does not yet hook into the dumping of autoloader when `composer dump-autoload` is used.
this PR adds support for class regeneration on `composer dump-autoload`.
we need this, since we use `composer install ... --no-scripts` in the CI pipeline and want to dump the autoloader on its own.
> dump the version class on "composer dump-autoload"

- .travis.yml
- composer.json
- composer.lock
I guess this will fix https://github.com/Ocramius/PackageVersions/issues/92
lets see what travis thinks
> updated dependencies

- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
no need to subscribe to install/update and autoload-dump.
fixes https://github.com/Ocramius/PackageVersions/issues/94
> the POST_AUTOLOAD_DUMP event also happens on composer install/update

- src/PackageVersions/FallbackVersions.php
- src/PackageVersions/Installer.php
- test/PackageVersionsTest/FallbackVersionsTest.php
- test/PackageVersionsTest/InstallerTest.php
Also be more clear in the messages why the exceptions are being thrown so that developers understand what files are being looked in for package versions. In other words, we know to deploy the `vendor/composer/installed.json` and/or the `composer.lock` for the project.
> Use vendor/composer/installed.json and fallback to using composer.lock

- .travis.yml
- src/PackageVersions/FallbackVersions.php
- test/PackageVersionsTest/E2EInstallerTest.php
Due to `getcwd()` returning an empty string in some environments, (or even `"."`, a dot, sometimes), this fallback versions logic was too fragile.
Adding hardcoded paths that are supposed to be constant (relative to the installation path of `FallbackVersions.php`) gives us more stability.
Fixes #101
> #101 corrected scanned locations for `installed.json` and `composer.json`

- composer.json
- src/PackageVersions/FallbackVersions.php
- src/PackageVersions/Installer.php
- test/PackageVersionsTest/FallbackVersionsTest.php
- test/PackageVersionsTest/InstallerTest.php
Due to #110, we discovered that in some cases, other Composer hooks could interfere with this package, triggering it before it's ready at first install.
#82 solves this issue already, but it's available in 1.5.0, which requires PHP 7.3. Since this package is used by `sentry/sentry` (which requires PHP 7.1), I'm backporting #82 to make this fix available to all Sentry users.
> Backport #82 to 1.4

- .travis.yml
- src/PackageVersions/Installer.php
- test/PackageVersionsTest/InstallerTest.php
- test/static-analysis/happy-path/expected-package-name.php
Note: the fallback version is **NOT** pure, because it does perform filesystem access.
> Ensure that, when generated, `PackageVersions\Versions::getVersion()` is `@psalm-pure`

- composer.json
- src/PackageVersions/FallbackVersions.php
- src/PackageVersions/Installer.php
- test/PackageVersionsTest/FallbackVersionsTest.php
As per https://github.com/composer/composer/issues/8726 - it'd be good to get popular plugins updated already to avoid blocking everyone later.
Ideally, you'd tag a new 1.4.3 release here so that people using PHP 7.1 and up get a chance to use Composer 2 in combination with this package.. In this case the old package versions won't be still usable as they'll break dependency resolution, so I hope this is enough reason for an exception. There is a `composer2-1.4` branch on my fork which applies cleanly on top of 1.4.2.
Note that to run update with composer 2 you need to use --ignore-platform-reqs as `dealerdirect/phpcodesniffer-composer-installer` is also not updated yet.
> Add support for Composer 2.x
